import '../../images/site/favicon.ico';
import '../../images/site/logo-56.png';
import '../../images/site/logo-100.png';
import '../../images/site/logo-192.png';
import '../../images/site/logo-512.png';
import '../../images/site/og_image.jpg';
import '../../images/site/og_image_2.jpg';
import '../../images/site/partners.jpg';

import '../../images/og/sreeram-collage.jpg';
import '../../images/og/berlin.gif';
import '../../images/og/indians-in-uk.jpg';
import '../../images/og/fortress.gif';
import '../../images/og/v-speech.gif';
import '../../images/og/cosmos.gif';
import '../../images/og/pale-blue-dot.jpg';
import '../../images/og/speech.jpg';
import '../../images/og/christopher-reeve.jpg';
import '../../images/og/zach-wahls.jpg';
