module.exports = [
  {
    title: 'Home',
    keywords: [ 'sreeram', 'sreeram padmanabhan' ],
    links: [
      {
        title: 'Home',
        ogTitle: 'Sreeram Padmanabhan - Web Artist | Web of thoughts',
        description: 'An artist of the web, perfectionist engineering the web using JavaScript. I emphasise on creativity, out of the box thinking and efficiency. Most important of all, I let my work do the talking!',
        ogDescription: 'An artist of the web, perfectionist engineering the web using JavaScript. I emphasise on creativity, out of the box thinking and efficiency. Most important of all, I let my work do the talking!',
        ogImage: '/img/og_image.jpg',
        route: '/post/home/home/home',
      },
    ],
  },
  {
    title: 'My Life experiences',
    links: [
      {
        title: 'My professional life so far',
        ogTitle: 'My professional life so far - Sreeram Padmanabhan',
        description: 'My professional life so far',
        ogDescription: 'My professional life so far',
        ogImage: '/img/sreeram-collage.jpg',
        route: '/post/personal/life/my-professional-life',
      },
      {
        title: 'How are Indians treated in Britain?',
        ogTitle: 'How are Indians treated in Britain? - Sreeram Padmanabhan',
        description: 'My experiences of living in the UK for 3 years',
        ogDescription: 'My experiences of living in the UK for 3 years',
        ogImage: '/img/indians-in-uk.jpg',
        route: '/post/personal/life/indians-in-britain',
      },
      {
        title: 'How I found a job in Germany',
        ogTitle: 'How I found a well paid job in Germany - Sreeram Padmanabhan',
        description: 'Secrets to getting that high paid job in a developed country',
        ogDescription: 'Secrets to getting that high paid job in a developed country',
        ogImage: '/img/berlin.gif',
        route: '/post/personal/life/job-in-berlin',
      },
    ],
  },
  {
    title: 'Inspirational speeches',
    keywords: [ 'inspirational speeches' ],
    links: [
      {
        title: 'Fortress of Solitude',
        ogTitle: 'Fortress of Solitude - Inpirational speeches',
        description: 'Jor el\'s speech in the fortress of solitude from Superman the Movie (1978)',
        ogDescription: 'Jor el\'s speech in the fortress of solitude from Superman the Movie (1978)',
        ogImage: '/img/fortress.gif',
        route: '/post/personal/inspirational/fortress-of-solitude',
      },
      {
        title: 'The V monologue',
        ogTitle: 'The V monologue - Inpirational speeches',
        description: 'The V speech from V for Vendetta (2005)',
        ogDescription: 'The V speech from V for Vendetta (2005)',
        ogImage: '/img/v-speech.gif',
        route: '/post/personal/inspirational/the-v-monologue',
      },
      {
        title: 'Atticus Finch',
        ogTitle: 'Atticus Finch - Inpirational speeches',
        description: 'Atticus Finch defends Tom Robinson with this great speech.',
        ogDescription: 'Atticus Finch defends Tom Robinson with this great speech.',
        ogImage: '/img/speech.jpg',
        route: '/post/personal/inspirational/atticus-finch',
      },
      {
        title: 'Carl Sagan - Pale Blue Dot',
        ogTitle: 'Carl Sagan\'s Pale blue dot speech - Inpirational speeches',
        description: 'Carl Sagan\'s description of the earth from the distant image Voyager sent',
        ogDescription: 'Carl Sagan\'s description of the earth from the distant image Voyager sent',
        ogImage: '/img/pale-blue-dot.jpg',
        route: '/post/personal/inspirational/pale-blue-dot',
      },
      {
        title: 'Carl Sagan - Edge of forever',
        ogTitle: 'Carl Sagan\'s Edge of forever speech - Inpirational speeches',
        description: 'An excerpt from an episode of Cosmos.',
        ogDescription: 'An excerpt from an episode of Cosmos.',
        ogImage: '/img/cosmos.gif',
        route: '/post/personal/inspirational/edge-of-forever',
      },
      {
        title: 'Christopher Reeve',
        ogTitle: 'Christopher Reeve - Hope in Motion - Inpirational speeches',
        description: 'An excerpt from Nothing is Impossible: Reflections on a New Life, a book by Christopher Reeve.',
        ogDescription: 'An excerpt from Nothing is Impossible: Reflections on a New Life, a book by Christopher Reeve.',
        ogImage: '/img/speech.jpg',
        route: '/post/personal/inspirational/christopher-reeve',
      },
      {
        title: 'Zach Wahls speech in 2011',
        ogTitle: 'Zach Wahls amazing speech - Inpirational speeches',
        description: 'Zach Walhs defends gay rights with this amazing speech.',
        ogDescription: 'Zach Walhs defends gay rights with this amazing speech.',
        ogImage: '/img/wahls.jpg',
        route: '/post/personal/inspirational/zach-wahls',
      },
    ],
  },
];