module.exports = [
  {
    title: 'Home',
    keywords: [],
    links: [
      {
        title: 'jsDrome',
        ogTitle: 'Open Graph Title',
        description: 'description',
        ogDescription: 'Open Graph Description',
        ogImage: '/img/og_image.jpg',
        route: '/post/home/home/home',
      },
    ],
  },
  {
    title: 'Web Development',
    keywords: [ 'web development', 'frontend development', 'javascript', 'node js', 'react', 'webpack' ],
    links: [
      {
        title: 'Initial commit',
        ogTitle: 'Initial Commit - Web of Thoughts - Sreeram Padmanabhan',
        description: 'The first commit of code.',
        ogDescription: 'The first commit of code.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/initial-commit',
      },
      {
        title: 'Configure Editorconfig',
        ogTitle: 'Editorconfig - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Configuring editorconfig.',
        ogDescription: 'Configuring editorconfig.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/editor-config',
      },
      {
        title: 'Configure Eslint',
        ogTitle: 'Eslint configuration - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Configuring eslint.',
        ogDescription: 'Configuring eslint.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/eslint-config',
      },
      {
        title: 'Entry point',
        ogTitle: 'Entry point Configuration - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Creating the first entry point.',
        ogDescription: 'Creating the first entry point.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/react-entry-point',
      },
      {
        title: 'Configure Babel',
        ogTitle: 'Babel configuration - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Configuring Babel to compile es6 to es5.',
        ogDescription: 'Configuring Babel to compile es6 to es5.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/babel-config',
      },
      {
        title: 'Webpack Dev setup',
        ogTitle: 'Webpack Dev Config - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to configure webpack to build for developement.',
        ogDescription: 'How to configure webpack to build for developement.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-dev-setup',
      },
      {
        title: 'Webpack Prod setup',
        ogTitle: 'Webpack Prod config - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Setting up Webpack for Production environments.',
        ogDescription: 'Setting up Webpack for Production environments.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-prod-setup',
      },
      {
        title: 'HTML Webpack Plugin',
        ogTitle: 'htmlWebpackPlugin - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to create index.html using HTMLWebpack Plugin.',
        ogDescription: 'How to create index.html using HTMLWebpack Plugin.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-html-webpack-plugin',
      },
      {
        title: 'Webpack common configuration',
        ogTitle: 'Webpack common config - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Refactoring webpack code.',
        ogDescription: 'Refactoring webpack code.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-common-config',
      },
      {
        title: 'Webpack Dev Server',
        ogTitle: 'WebpackDevServer - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to configure webpack dev server for local builds.',
        ogDescription: 'How to configure webpack dev server for local builds.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-dev-server',
      },
      {
        title: 'Firebase Hosting setup',
        ogTitle: 'Hosting your site in Firebase - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to host your static website in Firebase.',
        ogDescription: 'How to host your static website in Firebase.',
        ogImage: 'https://firebasestorage.googleapis.com/v0/b/zaxisapp.appspot.com/o/blog%2Ffirebase_head-750x354.png?alt=media&token=14d23c8e-2e2a-4f87-af1b-397b9a9be35e',
        route: '/post/tech/web/firebase-hosting',
      },
      {
        title: 'Circle CI Integration',
        ogTitle: 'Integrating your codebase with Circle CI - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to configure Circle CI to build your code automatically.',
        ogDescription: 'How to configure Circle CI to build your code automatically.',
        ogImage: 'https://firebasestorage.googleapis.com/v0/b/zaxisapp.appspot.com/o/blog%2Fundraw_following_q0cr.svg?alt=media&token=dace89b1-505d-4d83-9599-b1c05b1c8faa',
        route: '/post/tech/web/circle-ci-setup',
      },
      {
        title: 'Commit Message Linting',
        ogTitle: 'Enforcing commit message linting - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to make everyone follow similar commit practices.',
        ogDescription: 'How to make everyone follow similar commit practices.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/commit-message-linting',
      },
      {
        title: 'Hot Module Replacement',
        ogTitle: 'Hot module replacement - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-hot-module-replacement',
      },
      {
        title: 'Sourcemaps',
        ogTitle: 'Enabling Sourcemaps - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/sourcemaps',
      },
      {
        title: 'Clean Webpack Plugin',
        ogTitle: 'Clean Webpack plugin - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-clean-webpack-plugin',
      },
      {
        title: 'Documentation using JSDoc',
        ogTitle: 'Documentation generation using jsDoc - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/documentation-using-jsdoc',
      },
      {
        title: 'React entry point',
        ogTitle: 'React entry point - Sreeram Padmanabhan',
        description: 'Adding React as an entry point in a web app.',
        ogDescription: 'Adding React as an entry point in a web app.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/react-entry-point',
      },
      {
        title: 'React Router',
        ogTitle: 'React Router configuration - Sreeram Padmanabhan',
        description: 'Adding React router in a web app.',
        ogDescription: 'Adding React router in a web app.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/react-router',
      },
      {
        title: 'How Redux works',
        ogTitle: 'How does redux work under the hood? - Sreeram Padmanabhan',
        description: 'How do the view layer and the data layer work in conjunction?',
        ogDescription: 'How do the view layer and the data layer work in conjunction?',
        ogImage: '/img/redux.jpg',
        route: '/post/tech/web/how-redux-works',
      },
      {
        title: 'Webpack Bundle Analysis',
        ogTitle: 'Analysing Webpack\'s output bundle - Sreeram Padmanabhan',
        description: 'Analysing Webpack\'s output bundle using webpack-bundle-analyser plugin and webpack-visualizer plugins.',
        ogDescription: 'Analysing Webpack\'s output bundle using webpack-bundle-analyser plugin and webpack-visualizer plugins.',
        ogImage: '/img/visualizer-output.jpg',
        route: '/post/tech/web/webpack-bundle-analysis',
      },
      {
        title: 'Optimisation using Code Splitting',
        ogTitle: 'Optimisation using Code Splitting - Sreeram Padmanabhan',
        description: 'Code splitting using Split chunks plugin in webpack.',
        ogDescription: 'Code splitting using Split chunks plugin in webpack.',
        ogImage: 'https://firebasestorage.googleapis.com/v0/b/zaxisapp.appspot.com/o/blog%2Fwebpack-code-splitting.png?alt=media&token=6ee856ca-c9d4-41c4-b4ab-c8ad94e9be0b',
        route: '/post/tech/web/optimisation-using-code-splitting',
      },
      {
        title: 'Karma, Jasmine, Enzyme',
        ogTitle: 'Karma, Jasmine, Enzyme Configuration - Sreeram Padmanabhan',
        description: 'Configuring unit tests in frontend projects.',
        ogDescription: 'Configuring unit tests in frontend projects.',
        ogImage: '/img/karma-html-output.jpg',
        route: '/post/tech/web/unit-testing-using-karma-jasmine-enzyme',
      },
      {
        title: 'Code coverage using Istanbul',
        ogTitle: 'Code coverage using Istanbul - Sreeram Padmanabhan',
        description: 'Calculating code coverage in frontend projects.',
        ogDescription: 'Calculating code coverage in frontend projects.',
        ogImage: '/img/karma-html-output.jpg',
        route: '/post/tech/web/code-coverage-using-istanbul',
      },
    ],
  },
  {
    title: 'jsDrome Boilerplate',
    keywords: [],
    links: [
      {
        title: 'Features',
        route: '/post/setup/tutorials/features',
      },
      {
        title: 'Short cut way to setup',
        route: '/post/setup/tutorials/short-cut',
      },
      {
        title: 'Comprehensive way to setup',
        route: '/post/setup/tutorials/long-cut',
      },
      {
        title: 'Folder structure',
        route: '/post/setup/tutorials/folder-structure',
      },
      {
        title: 'Environment variables',
        route: '/post/setup/tutorials/environment-variables',
      },
      {
        title: 'Npm scripts',
        route: '/post/setup/tutorials/npm-scripts',
      },
      {
        title: 'Running App locally',
        route: '/post/setup/tutorials/running-app-locally',
      },
      {
        title: 'Creating a blog post',
        route: '/post/setup/tutorials/new-blog-post',
      },
    ],
  },
];