module.exports = [
  {
    title: 'Home',
    keywords: [ 'sreeram', 'sreeram padmanabhan' ],
    links: [
      {
        title: 'Sreeram Padmanabhan - Home',
        ogTitle: 'Sreeram Padmanabhan - Web Artist | Web of thoughts',
        description: 'An artist of the web, perfectionist engineering the web using JavaScript. I emphasise on creativity, out of the box thinking and efficiency. Most important of all, I let my work do the talking!',
        ogDescription: 'An artist of the web, perfectionist engineering the web using JavaScript. I emphasise on creativity, out of the box thinking and efficiency. Most important of all, I let my work do the talking!',
        ogImage: '/img/og_image.jpg',
        route: '/post/home/home/home',
      },
    ],
  },
  {
    title: 'My Photography',
    keywords: [ 'iphone photography' ],
    links: [
      {
        title: 'The best photo I\'ve ever taken',
        ogTitle: 'The best photo I\'ve ever taken - Sreeram Padmanabhan',
        description: 'I tried a bit of reflection photography in London.',
        ogDescription: 'I tried a bit of reflection photography in London.',
        ogImage: 'https://lh3.googleusercontent.com/_PFiXnhrPQmwCtBRo3jjpP1AGdayBJdlYtoENULWiMincscmWhwPtnOuGn3LaCeqtYk88Z_33zJj1eCr_05mSEj_Wlqm3jS8sZ0zmYKyWLiR9_YDuH21Y1JMtjseutauoo91SvzwODE6UoVWnxt47VHmGQj9Osie77EtfM3ngKV7x5ThY4irFwLlLV5GjTVBYxPamVBhnXNvpSLy9RdKX2xmBP9uCNGYfiTr8PPTlfdAO6vfehgUsVKK7MNz1vlXHj5cXmRRcOOXegVtlbFr8yf3t1CxhSB-bQPXF-rt-LL9KPp-RM9ceCb94Gp0XqCJK43WlAO_EmD-xrMa72vz8AXg1njG5R7GXgK4YD31Wq82sCPg0gw2Wq-4nWlGW6mCyO2y2UyojEIvaUNgQ-ADU9Fe1dT-8kFRIDdR-5uWn_h5XeOSK-ap2sm6SuY6Ssf-DV6deaXbu7BxuVRoL43RCQiYew0-uW2D-Imcoo24C_OEINYsw6NG4vVVr0RZLoJfUwhYf7V0REvNyzp1HoPEtq-tdtw7qEA0ELtIgaaEwf2BwH3lQVy8d9ldRfQw3MAww7rXNZuPuJjBKRIEMT_KPknMldl-UK77oz4pFSzqKSyBQG9_LMbOq-PIARN1Bg5Jsw_uJbjErpXa0IrFsudRqa0KUF4hz9iLKpghXeAL0JNDpd1_wSqj2Ok=s1754-no',
        route: '/post/personal/photos/london-eye-photo',
      },
      {
        title: 'The view from my home',
        ogTitle: 'The viw from my home in Trivandrum - Sreeram Padmanabhan',
        description: 'The breathtaking greenery of Trivandrum',
        ogDescription: 'The breathtaking greenery of Trivandrum',
        ogImage: 'https://lh3.googleusercontent.com/m6ME4lelNY_cWIu7qJRKyBX09zOed1Pa-kS5WW0hadjAUyi99KMNacqtOR-Sa_Y8qKzyseNAySmIat5T7E8E0Gm692xvvaUb-hVKlllobdj_3YAyfoOa5VFLFgLXz7hhgJsMtZSB1c0=w3351-h1754-no',
        route: '/post/personal/photos/view-from-home',
      },
      {
        title: 'Coolest thing I\'ve seen from an Airplane',
        ogTitle: 'The coolest thing I\'ve seen from an Airplane - Sreeram Padmanabhan',
        description: 'A view of the snow covered mountains stretching as far as I could see..',
        ogDescription: 'A view of the snow covered mountains stretching as far as I could see..',
        ogImage: 'https://qphs.fs.quoracdn.net/main-qimg-e7c3e6b75725d43e7355ca853d81ede8',
        route: '/post/personal/photos/snow-mountains',
      },
    ],
  },
  {
    title: 'My life experiences',
    keywords: [ 'life in uk', 'britain', 'germany', 'expat life', 'immigration', 'tax', 'indian' ],
    links: [
      {
        title: 'My professional life so far',
        ogTitle: 'My professional life so far - Sreeram Padmanabhan',
        description: 'How I built a successful career for myself.',
        ogDescription: 'How I built a successful career for myself.',
        ogImage: '/img/sreeram-collage.jpg',
        route: '/post/personal/life/my-professional-life',
      },
      {
        title: 'How are Indians treated in Britain?',
        ogTitle: 'How are Indians treated in Britain? - Sreeram Padmanabhan',
        description: 'My experiences of living in the UK for 3 years.',
        ogDescription: 'My experiences of living in the UK for 3 years.',
        ogImage: '/img/indians-in-uk.jpg',
        route: '/post/personal/life/indians-in-britain',
      },
      {
        title: 'My solo travel adventure',
        ogTitle: 'My solo travel adventure - Sreeram Padmanabhan',
        description: 'A short review of the cities and coutries I have been to.',
        ogDescription: 'A short review of the cities and coutries I have been to.',
        ogImage: '/img/solo-travel.jpg',
        route: '/post/personal/life/solo-travel',
      },
      {
        title: 'Things to do post moving to the UK',
        ogTitle: 'Things to do post moving to the UK - Sreeram Padmanabhan',
        description: 'These are some of the things I had to do when I first landed in the UK.',
        ogDescription: 'These are some of the things I had to do when I first landed in the UK.',
        ogImage: '/img/great-britain.jpg',
        route: '/post/personal/life/things-to-do-first-in-britain',
      },
      {
        title: 'How I found a job in Germany',
        ogTitle: 'How I found a well paid job in Germany - Sreeram Padmanabhan',
        description: 'Secrets to getting that high paid job in a developed country.',
        ogDescription: 'Secrets to getting that high paid job in a developed country.',
        ogImage: '/img/berlin.jpg',
        route: '/post/personal/life/job-in-berlin',
      },
      {
        title: 'Moving to Germany from India',
        ogTitle: 'Moving to Germany from India - Sreeram Padmanabhan',
        description: 'What does it take for an Indian to move to Germany?',
        ogDescription: 'What does it take for an Indian to move to Germany?',
        ogImage: '/img/berlin.jpg',
        route: '/post/personal/life/moving-to-germany',
      },
      {
        title: 'Things to do post moving to Germany',
        ogTitle: 'Things to do post moving to Germany - Sreeram Padmanabhan',
        description: 'These are the things I had to do when I moved to Germany.',
        ogDescription: 'These are the things I had to do when I moved to Germany.',
        ogImage: '/img/berlin.jpg',
        route: '/post/personal/life/things-to-do-first-in-germany',
      },
      {
        title: 'Things I tell my students',
        ogTitle: 'Things I tell my students - Sreeram Padmanabhan',
        description: 'The simple rules I follow to succeed I hope others find useful.',
        ogDescription: 'The simple rules I follow to succeed I hope others find useful.',
        // ogImage: '',
        route: '/post/personal/life/things-i-tell-my-students',
      },
      {
        title: 'Getting a web developer job',
        ogTitle: 'Getting a web developer job - Sreeram Padmanabhan',
        description: 'How hard can it be to become a Web developer?',
        ogDescription: 'How hard can it be to become a Web developer?',
        // ogImage: '',
        route: '/post/personal/career/web-developer-job',
      },
    ],
  },
  {
    title: 'Inspirational speeches',
    keywords: [ 'inspirational speeches' ],
    links: [
      {
        title: 'Carl Sagan - Pale Blue Dot',
        ogTitle: 'Carl Sagan\'s Pale blue dot speech - Inpirational speeches',
        description: 'Carl Sagan\'s description of the earth from the distant image Voyager sent.',
        ogDescription: 'Carl Sagan\'s description of the earth from the distant image Voyager sent.',
        ogImage: 'https://qphs.fs.quoracdn.net/main-qimg-e954b4948554c80e7181f07a00ddac99',
        route: '/post/personal/inspirational/pale-blue-dot',
      },
      {
        title: 'Fortress of Solitude',
        ogTitle: 'Fortress of Solitude - Inpirational speeches',
        description: 'Jor el\'s speech in the fortress of solitude from Superman the Movie (1978).',
        ogDescription: 'Jor el\'s speech in the fortress of solitude from Superman the Movie (1978).',
        ogImage: '/img/fortress.jpg',
        route: '/post/personal/inspirational/fortress-of-solitude',
      },
      {
        title: 'The V monologue',
        ogTitle: 'The V monologue - Inpirational speeches',
        description: 'The V speech from V for Vendetta (2005)',
        ogDescription: 'The V speech from V for Vendetta (2005)',
        ogImage: '/img/v-speech.jpg',
        route: '/post/personal/inspirational/the-v-monologue',
      },
      {
        title: 'Atticus Finch',
        ogTitle: 'Atticus Finch - Inpirational speeches',
        description: 'Atticus Finch defends Tom Robinson with this great speech in the movie To Kill a mockingbird.',
        ogDescription: 'Atticus Finch defends Tom Robinson with this great speech in the movie To Kill a mockingbird.',
        ogImage: '/img/speech.jpg',
        route: '/post/personal/inspirational/atticus-finch',
      },
      {
        title: 'Carl Sagan - Edge of forever',
        ogTitle: 'Carl Sagan\'s Edge of forever speech - Inpirational speeches',
        description: 'An excerpt from an episode of Cosmos.',
        ogDescription: 'An excerpt from an episode of Cosmos.',
        ogImage: '/img/cosmos.jpg',
        route: '/post/personal/inspirational/edge-of-forever',
      },
      {
        title: 'Christopher Reeve',
        ogTitle: 'Christopher Reeve - Hope in Motion - Inpirational speeches',
        description: 'An excerpt from Nothing is Impossible: Reflections on a New Life, a book by Christopher Reeve.',
        ogDescription: 'An excerpt from Nothing is Impossible: Reflections on a New Life, a book by Christopher Reeve.',
        ogImage: '/img/speech.jpg',
        route: '/post/personal/inspirational/christopher-reeve',
      },
      {
        title: 'Zach Wahls speech in 2011',
        ogTitle: 'Zach Wahls - Inpirational speeches',
        description: 'Zach Walhs defends gay rights with this amazing speech.',
        ogDescription: 'Zach Walhs defends gay rights with this amazing speech.',
        ogImage: '/img/zach-wahls.jpg',
        route: '/post/personal/inspirational/zach-wahls',
      },
    ],
  },
  {
    title: 'Web Development',
    keywords: [ 'web development', 'frontend development', 'javascript', 'node js', 'react', 'webpack' ],
    links: [
      {
        title: 'How I deploy to Production',
        ogTitle: 'How I deploy to production - Sreeram Padmanabhan',
        description: 'How to just push code and get it deployed to production automatically.',
        ogDescription: 'How to just push code and get it deployed to production automatically.',
        ogImage: '/img/automated-pipeline.jpg',
        route: '/post/tech/web/automated-pipeline',
      },
      {
        title: 'Machine configuration',
        ogTitle: 'A Web engineer\'s Toolkit - Sreeram Padmanabhan',
        description: 'Shiny new Macbook Pro, Node JS, Adobe Creative suite, and all kinds of softwares, browsers, emulators and extensions used by Web engineers.',
        ogDescription: 'Shiny new Macbook Pro, Node JS, Adobe Creative suite, and all kinds of softwares, browsers, emulators and extensions used by Web engineers.',
        ogImage: '/img/machine-configuration.jpg',
        route: '/post/tech/web/machine-configuration',
      },
      {
        title: 'Browser extensions',
        ogTitle: 'Must have browser extensions for Web engineers - Sreeram Padmanabhan',
        description: 'My favourite browser extensions which I use for frontend development.',
        ogDescription: 'My favourite browser extensions which I use for frontend development.',
        ogImage: '/img/browser-extensions.jpg',
        route: '/post/tech/web/browser-extensions',
      },
      {
        title: 'VS Code extensions',
        ogTitle: 'Top Visual Studio Code extensions for Web engineers - Sreeram Padmanabhan',
        description: 'My favourite Visual studio code extensions.',
        ogDescription: 'My favourite Visual studio code extensions.',
        ogImage: '/img/vscode-extensions.jpg',
        route: '/post/tech/web/vscode-extensions',
      },
      {
        title: 'VS Code preferences',
        ogTitle: 'My Visual Studio code preferences and settings - Sreeram Padmanabhan',
        description: 'My Vistual Studio Code preferences.',
        ogDescription: 'My Vistual Studio Code preferences.',
        ogImage: '/img/vscode-preferences.jpg',
        route: '/post/tech/web/vscode-preferences',
      },
      {
        title: 'Command line shortcuts',
        ogTitle: 'Top command line shortcuts for Web engineers - Sreeram Padmanabhan',
        description: 'My favourite command-line shortcuts.',
        ogDescription: 'My favourite command-line shortcuts.',
        ogImage: '/img/command-line-shortcuts.jpg',
        route: '/post/tech/web/aliases',
      },
      {
        title: 'Git aliases',
        ogTitle: 'Top must have git aliases for Web engineers - Sreeram Padmanabhan',
        description: 'My favourite git aliases I use on a daily basis.',
        ogDescription: 'My favourite git aliases I use on a daily basis.',
        ogImage: '/img/command-line-shortcuts.jpg',
        route: '/post/tech/web/git-aliases',
      },
      {
        title: 'Initial commit',
        ogTitle: 'Initial Commit - Web of Thoughts - Sreeram Padmanabhan',
        description: 'The first commit of code.',
        ogDescription: 'The first commit of code.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/initial-commit',
      },
      {
        title: 'Configure Editorconfig',
        ogTitle: 'Editorconfig - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Configuring editorconfig.',
        ogDescription: 'Configuring editorconfig.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/editor-config',
      },
      {
        title: 'Configure Eslint',
        ogTitle: 'Eslint configuration - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Configuring eslint.',
        ogDescription: 'Configuring eslint.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/eslint-config',
      },
      {
        title: 'Entry point',
        ogTitle: 'Entry point Configuration - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Creating the first entry point.',
        ogDescription: 'Creating the first entry point.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/react-entry-point',
      },
      {
        title: 'Configure Babel',
        ogTitle: 'Babel configuration - Web of Thoughts - Sreeram Padmanabhan',
        description: 'Configuring Babel to compile es6 to es5.',
        ogDescription: 'Configuring Babel to compile es6 to es5.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/babel-config',
      },
      {
        title: 'Webpack Dev setup',
        ogTitle: 'Setting up Webpack Dev configuration - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to configure webpack to build for developement.',
        ogDescription: 'How to configure webpack to build for developement.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-dev-setup',
      },
      {
        title: 'HTML Webpack Plugin',
        ogTitle: 'htmlWebpackPlugin - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to create index.html using HTMLWebpack Plugin.',
        ogDescription: 'How to create index.html using HTMLWebpack Plugin.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-html-webpack-plugin',
      },
      {
        title: 'Webpack Dev Server',
        ogTitle: 'WebpackDevServer - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to configure webpack dev server for local builds.',
        ogDescription: 'How to configure webpack dev server for local builds.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-dev-server',
      },
      {
        title: 'Commit Message Linting',
        ogTitle: 'Enforcing commit message linting - Web of Thoughts - Sreeram Padmanabhan',
        description: 'How to make everyone follow similar commit practices.',
        ogDescription: 'How to make everyone follow similar commit practices.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/commit-message-linting',
      },
      {
        title: 'Hot Module Replacement',
        ogTitle: 'Hot module replacement - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-hot-module-replacement',
      },
      {
        title: 'Webpack Prod setup',
        ogTitle: 'Setting up Webpack for Production environments - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-prod-setup',
      },
      {
        title: 'Webpack common configuration',
        ogTitle: 'Common Webpack configuration - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-common-config',
      },
      {
        title: 'Sourcemaps',
        ogTitle: 'Enabling Sourcemaps - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/sourcemaps',
      },
      {
        title: 'Clean Webpack Plugin',
        ogTitle: 'Clean Webpack plugin - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/webpack-clean-webpack-plugin',
      },
      {
        title: 'Documentation using JSDoc',
        ogTitle: 'Documentation generation using jsDoc - Web of Thoughts - Sreeram Padmanabhan',
        // description: '',
        // ogDescription: '',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/documentation-using-jsdoc',
      },
      {
        title: 'React entry point',
        ogTitle: 'React entry point - Sreeram Padmanabhan',
        description: 'Adding React as an entry point in a web app.',
        ogDescription: 'Adding React as an entry point in a web app.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/react-entry-point',
      },
      {
        title: 'React Router',
        ogTitle: 'React Router configuration - Sreeram Padmanabhan',
        description: 'Adding React router in a web app.',
        ogDescription: 'Adding React router in a web app.',
        ogImage: '/img/og_image.jpg',
        route: '/post/tech/web/react-router',
      },
      {
        title: 'How Redux works',
        ogTitle: 'How does redux work under the hood? - Sreeram Padmanabhan',
        description: 'How do the view layer and the data layer work in conjunction?',
        ogDescription: 'How do the view layer and the data layer work in conjunction?',
        ogImage: '/img/redux.jpg',
        route: '/post/tech/web/how-redux-works',
      },
      {
        title: 'Webpack Bundle Analysis',
        ogTitle: 'Analysing Webpack\'s output bundle - Sreeram Padmanabhan',
        description: 'Analysing Webpack\'s output bundle using webpack-bundle-analyser plugin and webpack-visualizer plugins.',
        ogDescription: 'Analysing Webpack\'s output bundle using webpack-bundle-analyser plugin and webpack-visualizer plugins.',
        ogImage: '/img/visualizer-output.jpg',
        route: '/post/tech/web/webpack-bundle-analysis',
      },
      {
        title: 'Optimisation using Code Splitting',
        ogTitle: 'Optimisation using Code Splitting - Sreeram Padmanabhan',
        description: 'Code splitting using Split chunks plugin in webpack.',
        ogDescription: 'Code splitting using Split chunks plugin in webpack.',
        ogImage: '/img/webpack-code-splitting.jpg',
        route: '/post/tech/web/optimisation-using-code-splitting',
      },
      {
        title: 'Karma, Jasmine, Enzyme',
        ogTitle: 'Karma, Jasmine, Enzyme Configuration - Sreeram Padmanabhan',
        description: 'Configuring unit tests in frontend projects.',
        ogDescription: 'Configuring unit tests in frontend projects.',
        ogImage: '/img/karma-html-output.jpg',
        route: '/post/tech/web/unit-testing-using-karma-jasmine-enzyme',
      },
      {
        title: 'Code coverage using Istanbul',
        ogTitle: 'Code coverage using Istanbul - Sreeram Padmanabhan',
        description: 'Calculating code coverage in frontend projects.',
        ogDescription: 'Calculating code coverage in frontend projects.',
        ogImage: '/img/karma-html-output.jpg',
        route: '/post/tech/web/code-coverage-using-istanbul',
      },
    ],
  },
  {
    title: 'Javascript concepts',
    keywords: [ 'javascript', 'closures', 'inheritance' ],
    links: [
      {
        title: 'Features of Javascript',
        ogTitle: 'What makes JavaScript different? - Sreeram Padmanabhan',
        description: 'Javascript is a world of its own. It has evolved from a browser only scripting language to a programming language of its own.',
        ogDescription: 'Javascript is a world of its own. It has evolved from a browser only scripting language to a programming language of its own.',
        ogImage: '/img/js.jpg',
        route: '/post/tech/javascript/javascript-features',
      },
      {
        title: 'Callback hell',
        ogTitle: 'Callback hell in Javascript - Sreeram Padmanabhan',
        description: 'An insight into the pyramid of doom scenario.',
        ogDescription: 'An insight into the pyramid of doom scenario.',
        ogImage: '/img/callback-hell.jpg',
        route: '/post/tech/javascript/callback-hell',
      },
      {
        title: 'Promises',
        ogTitle: 'Promises in JavaScript - Sreeram Padmanabhan',
        description: 'Promises solve the callback hell issue.',
        ogDescription: 'Promises solve the callback hell issue.',
        ogImage: '/img/promise.jpg',
        route: '/post/tech/javascript/promises',
      },
      {
        title: 'Async/Await',
        ogTitle: 'Async/Await in JavaScript - Sreeram Padmanabhan',
        description: 'An insight into async/await in ES7.',
        ogDescription: 'An insight into async/await in ES7.',
        ogImage: '/img/async-await.jpg',
        route: '/post/tech/javascript/async-await',
      },
      {
        title: 'Closures',
        ogTitle: 'What are closures in JavaScript? - Sreeram Padmanabhan',
        description: 'This is an attempt to better explain the example at W3 Schools for the same topic. Lets implement 2 counters. An up counter and a down counter. Lets look at the problems we face and their solutions.',
        ogDescription: 'This is an attempt to better explain the example at W3 Schools for the same topic. Lets implement 2 counters. An up counter and a down counter. Lets look at the problems we face and their solutions.',
        ogImage: '/img/closures-case-3-after.png',
        route: '/post/tech/javascript/closures',
      },
    ],
  },
];